# Generated by Django 6.0 on 2025-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='image/default.png', upload_to='images/profile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='username'),
        ),
    ]
