# Generated by Django 6.0 on 2025-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
